### ISSUE TITLE
Add descriptive text to the property editor

### ISSUE THREAD

**Issue by greystate** [vokseverk/Vokseverk.ColorSelector#1]
Something along the lines of:

```
"Input a valid CSS hex color: [             ] - or choose one of these presets: [  ] [  ] [  ]"
```

## Tasks

- [x] Add `<localize>` directives to view
- [x] Add `Lang` folder
- [x] Add `en-US.xml` + `en-GB.xml` (color vs. colour)
- [x] Add `da.xml`

Reference: https://our.umbraco.com/documentation/Extending/Packages/Language-Files-For-Packages/
